### ISSUE TITLE
模型路径变量建议

### ISSUE THREAD

**Issue by Seigi-Liuling** [Akegarasu/ChatGLM-webui#1]
model-path 默认值为 THUDM/chatglm-6b，与指引中 model/chatglm-6b 不一致且并未注明，容易造成误解，可否统一或在README中注明 

另，目前无模型直接运行会导致在当前系统的 .cache 文件夹下载并使用模型且不遵循源文件命名，可能影响Windows用户系统盘空间（若webui并不打算在系统盘），且存在用户日常用火绒等软件清理临时文件时将全部模型文件清理掉需要重下的风险，直接把https://huggingface.co/THUDM/chatglm-6b git clone到 model-path 应该更好？

**Comment by MatrixDoge** [comment]
我也赞同应该把--model-path写在README里面

第二个其实可以通过设置transformers.AutoModel.from_pretrained的cache_dir参数

**Comment by Akegarasu** [comment]
`THUDM/chatglm-6b` 是 huggingface 的 repo 目录。若未指定 `model-path` 会自动从这个 repo 下载模型。
