### ISSUE TITLE
官方仓库更新了流式输出，希望webui支持

### ISSUE THREAD

**Issue by xzqiaochu** [Akegarasu/ChatGLM-webui#16]
官方hugging face仓库已支持流式输出，调用接口为`model.stream_chat()`

**Comment by haofanurusai** [comment]
已提交，等待合并

**Comment by Akegarasu** [comment]
已支持

**Comment by lixiang1991** [comment]
补充一下。刚遇到这个错误。'ChatGLMForConditionalGeneration' object has no attribute 'stream_chat'。原来是https://huggingface.co/THUDM/chatglm-6b/tree/main更新了modeling_chatglm.py，替换一下就好了。
