### ISSUE TITLE
代码块高亮显示

### ISSUE THREAD

**Issue by xzqiaochu** [Akegarasu/ChatGLM-webui#18]
我这里无法高亮显示markdown代码框
![image](https://user-images.githubusercontent.com/41484968/226191204-a2ea42c4-bb47-42f9-8a5a-4340c2cd5152.png)
下图是控制台输出的原文本
![image](https://user-images.githubusercontent.com/41484968/226191293-29877198-fc54-4d28-8a56-463fd0cdf2a6.png)

**Comment by Akegarasu** [comment]
fixed.

**Comment by xzqiaochu** [comment]
修复好快，作者辛苦啦！

**Comment by xzqiaochu** [comment]
追问后bug仍存在
![image](https://user-images.githubusercontent.com/41484968/226198889-301c06da-35f8-4b35-b45c-b0c6ca4c8cbb.png)

**Comment by xzqiaochu** [comment]
补充：追问之后，如果下文出现了代码，则会在回答未完成时出现这个问题。回答完成后，所有的代码格式都恢复正常。

**Comment by Akegarasu** [comment]
回答未完成时，不会进行格式化。回答完成才会进行
