### ISSUE TITLE
多人同时对话问题

### ISSUE THREAD

**Issue by xzqiaochu** [Akegarasu/ChatGLM-webui#20]
如果一个客户端正在使用，另一个新打开的客户端并不知道，此时如果进行发送，会出现奇怪的问题。
具体是如下图：图1的客户端先问“简单介绍下自己”，AI回复到“我是ChatGLM,是清华大学KEG实验室和”的时候，图2的客户端插入问题：“你可以做什么”（此时图2客户端看到的是空白对话框）。最终产生了如下两张图的神奇效果。

图1
![image](https://user-images.githubusercontent.com/41484968/226195043-fd3e5aa3-49e9-4410-bf05-f621eb518cff.png)

图2
![image](https://user-images.githubusercontent.com/41484968/226195047-f11cb64b-bd41-428a-bef2-a92ca245ae6a.png)

**Comment by meta113** [comment]
你好，这个要在哪里下载呢？
