### ISSUE TITLE
对话报错

### ISSUE THREAD

**Issue by lbyczzz** [Akegarasu/ChatGLM-webui#30]
![image](https://user-images.githubusercontent.com/50623847/227089522-178600f4-c02f-4539-8565-c8eba6c5e24f.png)

**Comment by Akegarasu** [comment]
关闭服务器上的代理

**Comment by lbyczzz** [comment]
谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Akegarasu/ChatGLM-webui"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月23日(星期四) 中午11:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Akegarasu/ChatGLM-webui] 对话报错 (Issue #30)





 
Closed #30 as completed.
