### ISSUE TITLE
Could you make one for Apple Silicon mac?

### ISSUE THREAD

**Issue by Autumn-Whisper** [Akegarasu/ChatGLM-webui#4]
Thank you for providing the web UI! However, I am currently using a laptop with an RTX3060, which means that I am only able to use the CPU. Unfortunately, the CPU is too slow and the performance is not ideal. On the other hand, I also have a MacBook Air with an M2 processor and 16GB of RAM. Would it be possible for you to create a version of the UI that is compatible with Apple Silicon macs? I would greatly appreciate it if I could use the UI on my MacBook.

**Comment by zhouyihaocc** [comment]
you can use the cpu mode on mac, just add --cpu to the command when you start the webui. I'm also use mac to run this model and it works for me.

**Comment by Akegarasu** [comment]
`--cpu`
