### ISSUE TITLE
能加入局域网远程访问功能吗？

### ISSUE THREAD

**Issue by ZengWenJian123** [Akegarasu/ChatGLM-webui#40]
能加入局域网远程访问功能吗？不想抱着服务器在跟AI聊天了👋 ，或者说已经有方法能够实现局域网访问？

**Comment by l15y** [comment]
原项目基于gradio的webui已经可以实现，但是国内有些资源加载不方便
你可以试试我的ui，https://github.com/l15y/wenda

**Comment by Akegarasu** [comment]
`--listen`

**Comment by ZanoZ** [comment]
> 原项目基于gradio的webui已经可以实现，但是国内有些资源加载不方便 你可以试试我的ui，https://github.com/l15y/wenda

哈，刚刚从你那边看了一圈，也很不错，就是安装还有点费劲，我这里网不快

**Comment by ZengWenJian123** [comment]
谢谢你 兄弟
