### ISSUE TITLE
希望优化模型加载方式

### ISSUE THREAD

**Issue by Iteravse** [Akegarasu/ChatGLM-webui#42]
如题，目前的方式对于国内来说几乎必须挂梯子才能下载完整预训练模型，而启动后又必须关闭梯子不然就报错，但即便模型下载完过也必须联网自检，不然就报错，这很鸡肋，不挂梯子不能启动，挂完梯子又要关掉才能用，希望作者可以优化启动模型自检必须要联网自检的冗余步骤，thanks

**Comment by roj234** [comment]
自己去huggingface手动点击下载到本地，然后用--model参数指定到那文件夹
这样不会自检
