### ISSUE TITLE
web ui经常丢失回答

### ISSUE THREAD

**Issue by Arbow** [Akegarasu/ChatGLM-webui#5]
windows环境下运行，部分请求要7s以上响应，这时候web ui会频繁出现回答丢失，只有问一些简单的问题，回复后才会把之前的回答带回来。分析了一下，发现去掉 ui.queue().launch(..) 的queue() ，直接 ui.launch()就解决了。
看了下文档，这个queue()功能是为了解决60s以上返回的场景设计的，这里使用反而导致交互上出现问题。

**Comment by laose307** [comment]
能否告知下是修改哪个文件嘛？

**Comment by hjkl950217** [comment]
同问， 不知道是那个文件

**Comment by Arbow** [comment]
@laose307 @hjkl950217 新版已经解决此问题，不需要试了
