### ISSUE TITLE
gradio 出现style报错

### ISSUE THREAD

**Issue by xxWeiDG** [Akegarasu/ChatGLM-webui#71]
请问一下报了这个问题

usr/local/lib/python3.10/site-packages/gradio/components/textbox.py:259:` UserWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  warnings.warn(

看起来是style.css加载失败，但是路径已经设置对了还是没问题，不理解
![Screenshot from 2023-07-04 11-22-46](https://github.com/Akegarasu/ChatGLM-webui/assets/66368997/eccaea08-a81e-4b3d-89d2-d89b1d308c77)

**Comment by Lisilin87** [comment]
我遇到了同样的问题

**Comment by xxWeiDG** [comment]
> 我遇到了同样的问题
> 
> 

那你的功能能用吗

**Comment by Lisilin87** [comment]
不可以，https://github.com/gradio-app/gradio/issues/3472 这似乎是个解决方法，但是我还没有成功

**Comment by xxWeiDG** [comment]
> 不可以，[gradio-app/gradio#3472](https://github.com/gradio-app/gradio/issues/3472) 这似乎是个解决方法，但是我还没有成功

我换了一个，不尝试这个了

**Comment by FH-xk** [comment]
> 

你好，这个问题你解决了吗，我也遇到了一样的问题

**Comment by Lisilin87** [comment]
通过降低gradio的版本，我成功了（gradio==3.21.0）

**Comment by xxWeiDG** [comment]
> 通过降低gradio的版本，我成功了（gradio==3.12.0）

推理也可以正常使用吗

**Comment by xxWeiDG** [comment]
> > > 不可以，[gradio-app/gradio#3472](https://github.com/gradio-app/gradio/issues/3472) 这似乎是个解决方法，但是我还没有成功
> > 
> > 
> > 我换了一个，不尝试这个了
> 
> 你成功解决了吗？

没有
