### ISSUE TITLE
求助，更新最新版本后运行出错

### ISSUE THREAD

**Issue by hope-li279** [Akegarasu/ChatGLM-webui#72]
H:\软件\百度云网盘\BaiduNetdiskDownload\ChatGLM(1)\py310\lib\site-packages\gradio\deprecation.py:40: UserWarning: `height` is deprecated in `Interface()`, please use it within `launch()` instead.
  warnings.warn(value)
H:\软件\百度云网盘\BaiduNetdiskDownload\ChatGLM(1)\py310\lib\site-packages\gradio\deprecation.py:43: UserWarning: You have unused kwarg parameters in Textbox, please remove them: {'container': False}
  warnings.warn(
Traceback (most recent call last):
  File "H:\软件\百度云网盘\BaiduNetdiskDownload\ChatGLM(1)\webui.py", line 58, in <module>
    main()
  File "H:\软件\百度云网盘\BaiduNetdiskDownload\ChatGLM(1)\webui.py", line 45, in main
    ui.queue(concurrency_count=5, max_size=64).launch(
TypeError: Blocks.launch() got an unexpected keyword argument 'root_path'

**Comment by xiangledemianbizhe** [comment]
webui.py里后面几行有一行‘root_path=cmd_opts.path_prefix,’把这一行删掉之后虽然还是会报错前面的部分，但是可以正常运行了，用来应急还是可以的，好像是新版的gradio把root_path给删掉了，这里没改，就报错了。

**Comment by Akegarasu** [comment]
升级gradio

**Comment by sal-michael** [comment]
root_path=cmd_opts.path_prefix,
