### ISSUE TITLE
图1requirements文件好像没有指定好gradio版本，导致我重新安装之后一直卡在图2

### ISSUE THREAD

**Issue by SakuraRK** [Akegarasu/ChatGLM-webui#76]
图1:
![QUZZLZZ(EP{3D6 P E1V54D](https://github.com/Akegarasu/ChatGLM-webui/assets/95642715/702043c5-65e5-4a13-aaea-069870a3540d)
图2:
![AZWNL7C 1N8RZ87R_DT~IGN](https://github.com/Akegarasu/ChatGLM-webui/assets/95642715/f29de62c-c18d-4abe-81c4-98636ca22256)

**Comment by Akegarasu** [comment]
fixed
