### ISSUE TITLE
报错TypeError: Blocks.launch() got an unexpected keyword argument 'root_path'

### ISSUE THREAD

**Issue by SakuraRK** [Akegarasu/ChatGLM-webui#77]
![FET~XE)EC})SH{PBLR4@UWA](https://github.com/Akegarasu/ChatGLM-webui/assets/95642715/99cf0ec1-cb85-4883-b2c2-0d9b6abe8820)

**Comment by qm19** [comment]
我也遇到了同样的问题，请问解决了嘛？

**Comment by Akegarasu** [comment]
升级gradio

**Comment by SakuraRK** [comment]
> 升级gradio

如何升级呢？

**Comment by ShrLeeKNsword** [comment]
同问
