### ISSUE TITLE
Web报错Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by ZtRXR** [Akegarasu/ChatGLM-webui#8]
Expecting value: line 1 column 1 (char 0)
![image](https://user-images.githubusercontent.com/128154418/225914771-afd04b97-7e76-44bc-9a61-a4779cbb303b.png)

**Comment by Arbow** [comment]
看我提交的issue： https://github.com/Akegarasu/ChatGLM-webui/issues/5 ，把queue()去掉就正常了

**Comment by ZtRXR** [comment]
> 看我提交的issue： #5 ，把queue()去掉就正常了
是这样的，我按照你的方法修改成功运行了，感谢大佬！
